name: daily-tvl-update
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
      - name: Install node dependencies
        run: npm install
      - name: Run TVL file
        run: |
          node cronjob.js
          
        